import jsPDF from 'jspdf';

export interface PayslipData {
  businessName: string;
  businessCity: string;
  karigarName: string;
  karigarCode: string;
  wageType: string;
  periodLabel: string; // e.g. "June 2026"
  daysPresent: number;
  totalDays: number;
  unitsProduced?: number;
  pieceRate?: number;
  grossEarnings: number;
  peshgiDeduction: number;
  otherDeductions: number;
  netPay: number;
  currency: string;
}

export function generatePayslipPDF(data: PayslipData): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a5',
  });

  const W = 148; // A5 width in mm
  const margin = 14;
  let y = margin;

  const line = () => {
    doc.setLineWidth(0.3);
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, W - margin, y);
    y += 4;
  };

  const row = (
    label: string,
    value: string,
    bold = false,
    valueColor: [number, number, number] = [0, 0, 0]
  ) => {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(label, margin, y);
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setTextColor(...valueColor);
    doc.text(value, W - margin, y, { align: 'right' });
    y += 7;
  };

  const PKR = (n: number) =>
    `${data.currency} ${n.toLocaleString('en-PK', {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })}`;

  // ── HEADER ──
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text(data.businessName, W / 2, y, { align: 'center' });
  y += 7;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120, 120, 120);
  doc.text(data.businessCity, W / 2, y, { align: 'center' });
  y += 5;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('SALARY SLIP', W / 2, y, { align: 'center' });
  y += 5;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(data.periodLabel, W / 2, y, { align: 'center' });
  y += 8;

  line();

  // ── WORKER INFO ──
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('WORKER DETAILS', margin, y);
  y += 6;

  row('Name', data.karigarName);
  row('Code', data.karigarCode);
  row(
    'Pay Type',
    data.wageType === 'piece_rate'
      ? 'Piece Rate'
      : data.wageType === 'daily_wage'
      ? 'Daily Wage'
      : 'Monthly Salary'
  );
  row('Attendance', `${data.daysPresent} / ${data.totalDays} days`);
  y += 2;
  line();

  // ── EARNINGS ──
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('EARNINGS', margin, y);
  y += 6;

  if (data.wageType === 'piece_rate' && data.unitsProduced !== undefined) {
    row(
      'Units Produced',
      `${data.unitsProduced.toLocaleString()} × ${PKR(data.pieceRate || 0)}`
    );
  }

  row('Gross Earnings', PKR(data.grossEarnings));
  y += 2;
  line();

  // ── DEDUCTIONS ──
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('DEDUCTIONS', margin, y);
  y += 6;

  if (data.peshgiDeduction > 0) {
    row(
      'Peshgi (Advance)',
      `\u2212 ${PKR(data.peshgiDeduction)}`,
      false,
      [200, 80, 80]
    );
  }
  if (data.otherDeductions > 0) {
    row(
      'Other Deductions',
      `\u2212 ${PKR(data.otherDeductions)}`,
      false,
      [200, 80, 80]
    );
  }
  if (data.peshgiDeduction === 0 && data.otherDeductions === 0) {
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text('No deductions', margin, y);
    y += 7;
  }
  y += 2;
  line();

  // ── NET PAY ──
  doc.setFillColor(6, 7, 8);
  doc.roundedRect(margin, y, W - margin * 2, 14, 2, 2, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('NET PAY', margin + 4, y + 9);
  doc.setFontSize(12);
  doc.setTextColor(96, 165, 250);
  doc.text(PKR(data.netPay), W - margin - 4, y + 9, { align: 'right' });
  y += 20;

  // ── SIGNATURES ──
  line();
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 150, 150);
  doc.line(margin, y + 10, margin + 40, y + 10);
  doc.text('Worker Signature', margin, y + 14);
  doc.line(W - margin - 40, y + 10, W - margin, y + 10);
  doc.text('Employer Signature', W - margin - 40, y + 14);

  // ── FOOTER ──
  y += 22;
  doc.setFontSize(7);
  doc.setTextColor(180, 180, 180);
  doc.text(
    `Generated by Noxis Hub \u00B7 ${data.businessName} \u00B7 ${data.periodLabel}`,
    W / 2,
    y,
    { align: 'center' }
  );

  // Save
  const filename = `payslip_${data.karigarCode}_${data.periodLabel.replace(
    /\s/g,
    '_'
  )}.pdf`;
  doc.save(filename);
}
