import jsPDF from 'jspdf'
import 'jspdf-autotable'

interface ChallanData {
  businessName: string
  businessAddress?: string
  businessPhone?: string
  businessLogo?: string | null
  challanNumber: string
  challanDate: string
  dispatchOrder: {
    id: string
    vehicle_number?: string
    driver_name?: string
    delivery_address?: string
    notes?: string
  }
  party: {
    name: string
    address?: string
    phone?: string
  }
  items: Array<{
    name: string
    quantity: number
    unit: string
    remarks?: string
  }>
  currency: string
}

export function generateDeliveryChallan(data: ChallanData): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a5',
  })

  const PAGE_W = 148
  const MARGIN = 12
  let y = MARGIN

  // ── HEADER ──
  doc.setFillColor(6, 7, 8)
  doc.rect(0, 0, PAGE_W, 28, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(data.businessName, MARGIN, 10)

  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  if (data.businessPhone) {
    doc.text(data.businessPhone, MARGIN, 16)
  }
  if (data.businessAddress) {
    doc.text(data.businessAddress, MARGIN, 21, { maxWidth: PAGE_W - MARGIN * 2 })
  }

  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(96, 165, 250)
  doc.text('DELIVERY CHALLAN', PAGE_W - MARGIN, 10, { align: 'right' })

  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(200, 200, 200)
  doc.text(`#${data.challanNumber}`, PAGE_W - MARGIN, 16, { align: 'right' })
  doc.text(data.challanDate, PAGE_W - MARGIN, 21, { align: 'right' })

  y = 34

  // ── DELIVERY / VEHICLE INFO ──
  doc.setTextColor(0, 0, 0)

  const leftCol = MARGIN
  const rightCol = PAGE_W / 2 + 4

  // Left: Party / Deliver To
  doc.setFillColor(245, 245, 245)
  doc.rect(leftCol, y, 58, 28, 'F')
  doc.setFontSize(7)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(100, 100, 100)
  doc.text('DELIVER TO', leftCol + 3, y + 5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(9)
  doc.text(data.party.name, leftCol + 3, y + 11, { maxWidth: 52 })
  if (data.party.address) {
    doc.setFontSize(7)
    doc.text(data.party.address, leftCol + 3, y + 18, { maxWidth: 52 })
  }
  if (data.party.phone) {
    doc.setFontSize(7)
    doc.text(data.party.phone, leftCol + 3, y + 25)
  }

  // Right: Vehicle info
  doc.setFillColor(245, 245, 245)
  doc.rect(rightCol, y, 58, 28, 'F')
  doc.setFontSize(7)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(100, 100, 100)
  doc.text('TRANSPORT', rightCol + 3, y + 5)

  const transportInfo: [string, string][] = [
    ['Vehicle #', data.dispatchOrder.vehicle_number || '—'],
    ['Driver', data.dispatchOrder.driver_name || '—'],
  ]

  transportInfo.forEach(([label, value], i) => {
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(80, 80, 80)
    doc.setFontSize(7)
    doc.text(label + ':', rightCol + 3, y + 12 + i * 7)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(8)
    doc.text(value, rightCol + 22, y + 12 + i * 7)
  })

  y += 34

  // ── ITEMS TABLE ──
  ;(doc as any).autoTable({
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [['#', 'Item / Description', 'Quantity', 'Unit', 'Remarks']],
    body: data.items.map((item, i) => [
      String(i + 1),
      item.name,
      item.quantity.toLocaleString('en-PK'),
      item.unit,
      item.remarks || '',
    ]),
    styles: { fontSize: 8, cellPadding: 2.5 },
    headStyles: {
      fillColor: [6, 7, 8],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 7,
    },
    columnStyles: {
      0: { cellWidth: 8, halign: 'center' },
      2: { cellWidth: 18, halign: 'right' },
      3: { cellWidth: 14, halign: 'center' },
      4: { cellWidth: 24 },
    },
    alternateRowStyles: { fillColor: [249, 249, 249] },
  })

  y = (doc as any).lastAutoTable.finalY + 8

  // ── SIGNATURES ──
  const sigWidth = 38
  const gap = (PAGE_W - MARGIN * 2 - sigWidth * 3) / 2

  const sigs = ['Prepared By', 'Checked By', 'Received By']

  sigs.forEach((label, i) => {
    const sx = MARGIN + i * (sigWidth + gap)
    doc.setDrawColor(180, 180, 180)
    doc.line(sx, y + 14, sx + sigWidth, y + 14)
    doc.setFontSize(7)
    doc.setTextColor(120, 120, 120)
    doc.setFont('helvetica', 'bold')
    doc.text(label, sx + sigWidth / 2, y + 18, { align: 'center' })
  })

  // ── FOOTER ──
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(6)
    doc.setTextColor(180, 180, 180)
    doc.text(
      `Page ${i} of ${pageCount} · ${data.challanNumber} · Generated by Noxis Hub`,
      PAGE_W / 2,
      doc.internal.pageSize.height - 6,
      { align: 'center' }
    )
  }

  doc.save(`Challan-${data.challanNumber}.pdf`)
}
