/**
 * Phase 11: Branching & Logistics Terminology
 * These strings should be synchronized with the `industry_personas` table in the database.
 */

export const phase11Strings = {
  // --- DEFAULT / INTERNATIONAL (English) ---
  default: {
    "branches.title": "Network Management",
    "branches.subtitle": "Facility Locations",
    "branches.new_branch": "Add New Site",
    "branches.code": "Site Code",
    "branches.name": "Facility Name",
    "branches.city": "City",
    "branches.address": "Full Address",
    "branches.timezone": "Timezone",
    "branches.manager": "Site Manager",
    "branches.headquarters": "Headquarters",
    "branches.status.active": "Operational",
    "branches.status.suspended": "Suspended",
    "branches.status.archived": "Decommissioned",
    "branches.count": "{count} of {max} sites used",
    "branches.hq_badge": "HQ",
    "branches.suspend_confirm": "Suspend operations at this site?",
    "branches.archive_confirm": "Decommission this site permanently?",
    "branches.archive_type_confirm": "Type site name to confirm decommissioning",
    "transfer.inter_branch_title": "Inter-Site Logistics",
    "transfer.from_branch": "Origin Site",
    "transfer.to_branch": "Destination Site",
    "transfer.sku": "Item",
    "transfer.qty_available": "Qty available at origin",
    "transfer.initiate": "Commence Transfer",
    "transfer.receive": "Acknowledge Receipt",
    "transfer.cancel": "Abort Transfer",
    "transfer.status.in_transit": "In Transit",
    "transfer.status.received": "Acknowledged",
    "transfer.status.cancelled": "Aborted",
    "transfer.insufficient_stock": "Insufficient stock at origin site",
    "finance.branch_filter": "Filter by Site",
    "finance.all_branches_consolidated": "Consolidated Network View",
    "finance.stock_valuation_title": "Network Stock Valuation",
    "portal.dashboard.title": "Account Overview",
    "portal.dashboard.total_outstanding": "Balance Due",
    "portal.dashboard.overdue": "Overdue",
    "portal.dashboard.last_payment": "Last Payment",
    "portal.dashboard.next_due": "Next Due Date",
    "portal.dashboard.recent_invoices": "Recent Invoices",
    "portal.invoices.title": "Invoices & Billing",
    "portal.invoices.invoice_no": "Invoice #",
    "portal.invoices.date": "Date",
    "portal.invoices.due_date": "Due Date",
    "portal.invoices.amount": "Total",
    "portal.invoices.paid": "Paid",
    "portal.invoices.outstanding": "Remaining",
    "portal.invoices.status": "Status",
    "portal.invoices.pay_now": "Pay Balance",
    "portal.invoices.download": "Download PDF",
    "portal.invoices.view_all": "View Statement",
    "portal.invoices.empty": "No invoices found. Contact the billing department for details.",
    "portal.invoices.overdue_warning": "Payment is past due",
    "portal.status.paid": "Paid",
    "portal.status.partial": "Partial",
    "portal.status.overdue": "Overdue",
    "portal.status.pending": "Pending",
    "portal.management_title": "Client Access Control",
    "portal.invite_client": "Grant Portal Access",
    "portal.resend_invite": "Resend Magic Link",
    "portal.suspend_access": "Suspend Client Session",
    "portal.revoke_access": "Revoke Access Permanently",
    "portal.preview_mode": "PREVIEW MODE",
    "portal.outstanding_balance": "Balance Outstanding",
    "portal.last_login": "Last Login",
    "portal.invite_sent": "Invite Dispatched",
    "portal.welcome": "Greetings, {name}",
    "portal.total_outstanding": "Total Balance Due",
    "portal.overdue_amount": "Past Due",
    "portal.all_clear": "Accounts Clear",
    "portal.last_payment": "Recent Activity",
    "portal.next_due_date": "Next Maturity",
    "portal.invoice_number": "Reference ID",
    "portal.invoice_date": "Issued Date",
    "portal.due_date": "Maturity Date",
    "portal.amount_paid": "Settled Amount",
    "portal.pay_now": "Settle Now",
    "portal.download_pdf": "Retrieve PDF",
    "portal.payment_success": "Settlement successful.",
    "portal.payment_error_declined": "Payment declined by provider.",
    "portal.payment_error_generic": "System error during settlement.",
    "portal.link_expired": "Access link has expired.",
    "portal.request_new_link": "Request New Access",
    "portal.verifying_access": "Verifying Credentials",
    "portal.no_invoices": "No records found.",
    "portal.partial_payment_label": "Partial Settlement",
    "portal.select_payment_method": "Choose Provider",
    "portal.auth_expired": "Session expired.",
    "portal.session_invalid": "Unauthorized access attempt.",
    "portal.client_name": "Client Name",
    "portal.party": "Partner",
    "portal.status": "Status",
    "portal.never": "Never",
    "portal.active_nodes": "{count} active stakeholder nodes",
    "portal.initialize_access": "Initialize Access",
    "portal.select_partner": "Select Industrial Partner",
    "portal.select_party_placeholder": "Select Party...",
    "portal.access_email": "Access Email",
    "portal.display_name": "Display Name",
    "portal.dispatch_invite": "Dispatch Access Invite",
    "stock.sku": "SKU",
    "stock.product_name": "Product Name",
    "stock.qty_on_hand": "Qty On Hand",
    "stock.location": "Location",
    "procurement.inventory_healthy": "Inventory Levels Healthy",
    "procurement.replenishment_alert": "Automated Replenishment Alert",
    "procurement.items_below_reorder": "{count} items below reorder level",
    "procurement.total_est_value": "{value} total estimated value",
    "procurement.view_all": "View All",
    "procurement.current_stock": "Current Stock",
    "procurement.shortfall": "Shortfall",
    "procurement.est_cost": "Est. Cost",
    "procurement.create_draft_po": "Create Draft PO",
    "payroll.no_whatsapp": "No WhatsApp number configured for this Karigar.",
    "payroll.salary_statement": "Salary Statement",
    "payroll.recipient_artisan": "Recipient Artisan",
    "payroll.period_label": "Period Label",
    "payroll.earnings": "Earnings",
    "payroll.piece_rate": "Piece Rate Output",
    "payroll.daily_wage": "Daily Wage",
    "payroll.monthly_base": "Monthly Base",
    "payroll.overtime": "Overtime (1.5x)",
    "payroll.total_gross": "Total Gross",
    "payroll.deductions": "Deductions",
    "payroll.advance_settled": "Advance (Peshgi) Settled",
    "payroll.eobi": "EOBI Contribution",
    "payroll.sessi": "SESSI Deduction",
    "payroll.other_adj": "Other Adjustments",
    "payroll.total_deductions": "Total Deductions",
    "payroll.net_disbursable": "Net Disbursable Amount",
    "payroll.days_present": "Days Present",
    "payroll.total_output": "Total Output",
    "payroll.units": "Units",
    "payroll.efficiency": "Efficiency %",
    "payroll.export_pdf": "Export PDF Slip",
    "payroll.send_whatsapp": "Send via WhatsApp",
    "select_branch": "Select Location",
    "log_out": "Terminate Session",
    "cctv.sentinel_title": "Sentinel: Site Surveillance Nodes",
    "cctv.live_active": "Live Intelligence Active",
    "cctv.exterior": "Exterior",
    "cctv.streaming": "Streaming",
    "security.alert_title": "Forensic Security Alert",
    "security.violation_detected": "System Integrity Violation Detected",
    "security.target_node": "Target Node",
    "security.violation_type": "Violation Type",
    "security.manual_ack": "Manual Acknowledgement Required",
    "security.type_to_confirm": "Type \"{node}\" to confirm...",
    "security.posting_audit": "Posting to Audit Trail...",
    "security.ack_violation": "Acknowledge Violation",
    "security.alert_id": "Alert ID",
    "security.triggered": "Triggered",
    "brand.name": "NOXIS",
    "brand.hub_version": "v13.0",
    "nav_dashboard": "Dashboard",
    "nav_generators": "Generators",
    "nav_calculators": "Calculators",
    "nav_messaging": "Messaging",
    "nav_pairing": "Device Pairing",
    "nav_invoices": "Invoices",
    "nav_payroll": "Payroll",
    "nav_parties": "Parties",
    "nav_cctv": "Security",
    "nav_dispatch": "Dispatch",
    "nav_production": "Production",
    "nav_karigars": "Karigars",
    "nav_reports": "Reports",
    "nav_settings": "Settings",
    "nav_stock": "Stock",
    "nav_inventory": "Inventory",
    "nav_lens": "Noxis Lens",
    "nav_converters": "Unit Converters",
    "nav_file_morph": "PDF & File Tools",
    "nav_import": "Smart Import"
  },

  // --- SOUTH ASIAN (Urdu/Roman Urdu Context) ---
  south_asian: {
    "branches.title": "Godown & Site Management",
    "branches.subtitle": "Operational Locations",
    "branches.new_branch": "Naya Godown",
    "branches.code": "Godown Code",
    "branches.name": "Site ka Naam",
    "branches.city": "Shehar",
    "branches.address": "Mukammal Pata",
    "branches.timezone": "Timezone",
    "branches.manager": "Godown In-charge",
    "branches.headquarters": "Markazi Godown (HQ)",
    "branches.status.active": "Active",
    "branches.status.suspended": "Muattal (Suspended)",
    "branches.status.archived": "Archived",
    "branches.count": "10 mein se {count} sites istemal mein hain",
    "branches.hq_badge": "Markazi",
    "branches.suspend_confirm": "Kya aap is site ko muattal (suspend) karna chahte hain?",
    "branches.archive_confirm": "Kya aap is site ko hamesha ke liye khatam (archive) karna chahte hain?",
    "branches.archive_type_confirm": "Confirm karne ke liye site ka naam likhein",
    "transfer.inter_branch_title": "Ek Godown se Dusre mein Muntaqili",
    "transfer.from_branch": "Kahan se (Origin)",
    "transfer.to_branch": "Kahan ko (Destination)",
    "transfer.sku": "Maal / Item",
    "transfer.qty_available": "Origin par maujooda miqdar",
    "transfer.initiate": "Muntaqili Shuru Karein",
    "transfer.receive": "Maal Wasool Karein",
    "transfer.cancel": "Muntaqili Mansookh Karein",
    "transfer.status.in_transit": "Raste mein hai",
    "transfer.status.received": "Wasool ho gaya",
    "transfer.status.cancelled": "Mansookh shuda",
    "transfer.insufficient_stock": "Origin godown mein maal kam hai",
    "finance.branch_filter": "Site ke mutabiq filter",
    "finance.all_branches_consolidated": "Tamam sites ka majmua",
    "finance.stock_valuation_title": "Kul Stock ki Qimat",
    "portal.dashboard.title": "Account ki Tafseelat",
    "portal.dashboard.total_outstanding": "Wajib-ul-Ada",
    "portal.dashboard.overdue": "Der-shuda",
    "portal.dashboard.last_payment": "Akhri Adaiyagi",
    "portal.dashboard.next_due": "Agli Tareekh",
    "portal.dashboard.recent_invoices": "Haliya Bills",
    "portal.invoices.title": "Bills aur Adaiyagi",
    "portal.invoices.invoice_no": "Bill Number",
    "portal.invoices.date": "Tareekh",
    "portal.invoices.due_date": "Ada karne ki Tareekh",
    "portal.invoices.amount": "Kul Raqam",
    "portal.invoices.paid": "Ada shuda",
    "portal.invoices.outstanding": "Baqaya Raqam",
    "portal.invoices.status": "Halat",
    "portal.invoices.pay_now": "Raqam Ada Karein",
    "portal.invoices.download": "PDF Download",
    "portal.invoices.view_all": "Mukammal Statement",
    "portal.invoices.empty": "Koi bill nahi mila. Tafseelat ke liye daftar se rabta karein.",
    "portal.invoices.overdue_warning": "Adaiyagi ki tareekh guzar chuki hai",
    "portal.status.paid": "Ada ho gaya",
    "portal.status.partial": "Baqaya",
    "portal.status.overdue": "Der-shuda",
    "portal.status.pending": "Pending",
    "portal.management_title": "Client Portal Control",
    "portal.invite_client": "Naya Access Dein",
    "portal.resend_invite": "Dobara Link Bhejein",
    "portal.suspend_access": "Access Muattal Karein",
    "portal.revoke_access": "Access Khatam Karein",
    "portal.preview_mode": "PREVIEW MODE",
    "portal.outstanding_balance": "Baqaya Raqam",
    "portal.last_login": "Akhri Login",
    "portal.invite_sent": "Invite Bhej Diya",
    "portal.welcome": "Khush amdeed, {name}",
    "portal.total_outstanding": "Kul Wajib-ul-Ada",
    "portal.overdue_amount": "Der-shuda Raqam",
    "portal.all_clear": "Koi Baqaya Nahi",
    "portal.last_payment": "Haliya Adaiyagi",
    "portal.next_due_date": "Agli Tareekh",
    "portal.invoice_number": "Bill ID",
    "portal.invoice_date": "Bill ki Tareekh",
    "portal.due_date": "Ada karne ki Tareekh",
    "portal.amount_paid": "Ada shuda",
    "portal.pay_now": "Abhi Ada Karein",
    "portal.download_pdf": "PDF Download",
    "portal.payment_success": "Adaiyagi kamyab rahi.",
    "portal.payment_error_declined": "Adaiyagi nakaam rahi.",
    "portal.payment_error_generic": "System mein kharabi.",
    "portal.link_expired": "Link ki muddat khatam ho chuki hai.",
    "portal.request_new_link": "Naya Link Mangwaein",
    "portal.verifying_access": "Tasdeeq ho rahi hai",
    "portal.no_invoices": "Koi record nahi mila.",
    "portal.partial_payment_label": "Baqaya Adaiyagi",
    "portal.select_payment_method": "Zariya-e-Adaiyagi",
    "portal.auth_expired": "Session khatam.",
    "portal.session_invalid": "Ghair tasdeeq shuda koshish.",
    "portal.client_name": "Client ka Naam",
    "portal.party": "Partner",
    "portal.status": "Halat",
    "portal.never": "Kabhi nahi",
    "portal.active_nodes": "{count} active stakeholder nodes",
    "portal.initialize_access": "Initialize Access",
    "portal.select_partner": "Partner Muntakhib Karein",
    "portal.select_party_placeholder": "Partner Chunien...",
    "portal.access_email": "Access Email",
    "portal.display_name": "Display Name",
    "portal.dispatch_invite": "Invite Bhejein",
    "stock.sku": "SKU",
    "stock.product_name": "Item ka Naam",
    "stock.qty_on_hand": "Maujooda Miqdar",
    "stock.location": "Jagah / Location",
    "procurement.inventory_healthy": "Stock ki halat behtar hai",
    "procurement.replenishment_alert": "Stock Alert",
    "procurement.items_below_reorder": "{count} items kam ho gaye hain",
    "procurement.total_est_value": "{value} kul andazan qimat",
    "procurement.view_all": "Sab Dekhein",
    "procurement.current_stock": "Maujooda Stock",
    "procurement.shortfall": "Kammi",
    "procurement.est_cost": "Andazan Qimat",
    "procurement.create_draft_po": "Naya PO Banayein",
    "payroll.no_whatsapp": "Is Karigar ka WhatsApp number nahi mila.",
    "payroll.salary_statement": "Salary Statement",
    "payroll.recipient_artisan": "Karigar ka Naam",
    "payroll.period_label": "Period",
    "payroll.earnings": "Kamai (Earnings)",
    "payroll.piece_rate": "Piece Rate Kaam",
    "payroll.daily_wage": "Rozana Mazdoori",
    "payroll.monthly_base": "Mahana Tankhwah",
    "payroll.overtime": "Overtime (1.5x)",
    "payroll.total_gross": "Kul Kamai",
    "payroll.deductions": "Katautiyan (Deductions)",
    "payroll.advance_settled": "Advance (Peshgi) ki Wapsi",
    "payroll.eobi": "EOBI ki Katauti",
    "payroll.sessi": "SESSI ki Katauti",
    "payroll.other_adj": "Digar Adjustments",
    "payroll.total_deductions": "Kul Katauti",
    "payroll.net_disbursable": "Net Takhwah",
    "payroll.days_present": "Hazri (Din)",
    "payroll.total_output": "Kul Kaam",
    "payroll.units": "Units",
    "payroll.efficiency": "Efficiency %",
    "payroll.export_pdf": "Slip Download Karein",
    "payroll.send_whatsapp": "WhatsApp Bhejein",
    "security.alert_title": "Forensic Security Alert",
    "security.violation_detected": "System Integrity Violation Detected",
    "security.target_node": "Target Node",
    "security.violation_type": "Violation Type",
    "security.manual_ack": "Manual Acknowledgement Required",
    "security.type_to_confirm": "Type \"{node}\" to confirm...",
    "security.posting_audit": "Posting to Audit Trail...",
    "security.ack_violation": "Acknowledge Violation",
    "security.alert_id": "Alert ID",
    "security.triggered": "Triggered",
    "brand.name": "NOXIS",
    "brand.hub_version": "HUB v13.0",
    "nav_dashboard": "Dashboard",
    "nav_generators": "ڈاکومنٹ جنریٹر",
    "nav_calculators": "کیلکولیٹر",
    "nav_messaging": "پیغام رسانی",
    "nav_pairing": "ڈیوائس جوڑی",
    "nav_invoices": "انوائس",
    "nav_payroll": "تنخواہ",
    "nav_parties": "فریق",
    "nav_cctv": "سیکیورٹی",
    "nav_dispatch": "ترسیل",
    "nav_production": "پیداوار",
    "nav_karigars": "کاریگر",
    "nav_reports": "رپورٹس",
    "nav_settings": "ترتیبات",
    "nav_stock": "اسٹاک",
    "nav_inventory": "انوینٹری",
    "nav_lens": "نوکس لینس",
    "nav_converters": "یونٹ کنورٹرز",
    "nav_file_morph": "پی ڈی ایف اور فائل ٹولز",
    "nav_import": "اسمارٹ امپورٹ"
  },

  // --- REGIONAL (Specialized Textile/Industrial) ---
  industrial_specialized: {
    "branches.title": "Branch Management",
    "branches.subtitle": "Industrial Sites",
    "branches.new_branch": "Add New Branch",
    "branches.code": "Branch Code",
    "branches.name": "Branch Name",
    "branches.city": "City",
    "branches.address": "Full Address",
    "branches.timezone": "Timezone",
    "branches.manager": "Branch Manager",
    "branches.headquarters": "Headquarters",
    "branches.status.active": "Active",
    "branches.status.suspended": "Suspended",
    "branches.status.archived": "Closed",
    "branches.count": "{count} / 10 active branches",
    "branches.hq_badge": "HQ",
    "branches.suspend_confirm": "Suspend operations at this branch?",
    "branches.archive_confirm": "Close this branch permanently?",
    "branches.archive_type_confirm": "Type branch name to confirm",
    "transfer.inter_branch_title": "Inter-Branch Stock Transfer",
    "transfer.from_branch": "Source Branch",
    "transfer.to_branch": "Target Branch",
    "transfer.sku": "Item / SKU",
    "transfer.qty_available": "Source Stock",
    "transfer.initiate": "Start Transfer",
    "transfer.receive": "Receive Stock",
    "transfer.cancel": "Cancel Transfer",
    "transfer.status.in_transit": "In Transit",
    "transfer.status.received": "Received",
    "transfer.status.cancelled": "Cancelled",
    "transfer.insufficient_stock": "Insufficient stock at source",
    "finance.branch_filter": "Branch Filter",
    "finance.all_branches_consolidated": "Consolidated View",
    "finance.stock_valuation_title": "Total Stock Valuation",
    "portal.dashboard.title": "Account Summary",
    "portal.dashboard.total_outstanding": "Balance Due",
    "portal.dashboard.overdue": "Overdue",
    "portal.dashboard.last_payment": "Last Payment",
    "portal.dashboard.next_due": "Due Date",
    "portal.dashboard.recent_invoices": "Recent Bills",
    "portal.invoices.title": "Statement of Account",
    "portal.invoices.invoice_no": "Bill #",
    "portal.invoices.date": "Date",
    "portal.invoices.due_date": "Due Date",
    "portal.invoices.amount": "Total Amount",
    "portal.invoices.paid": "Paid",
    "portal.invoices.outstanding": "Baqaya",
    "portal.invoices.status": "Status",
    "portal.invoices.pay_now": "Pay Now",
    "portal.invoices.download": "Download PDF",
    "portal.invoices.view_all": "View All",
    "portal.invoices.empty": "No records found.",
    "portal.invoices.overdue_warning": "Past Due",
    "portal.status.paid": "Paid",
    "portal.status.partial": "Partial",
    "portal.status.overdue": "Overdue",
    "portal.status.pending": "Pending",
    "portal.management_title": "Customer Portal Control",
    "portal.invite_client": "Add Customer Access",
    "portal.resend_invite": "Resend Link",
    "portal.suspend_access": "Suspend Access",
    "portal.revoke_access": "Remove Access",
    "portal.preview_mode": "PREVIEW",
    "portal.outstanding_balance": "Total Due",
    "portal.last_login": "Last Activity",
    "portal.invite_sent": "Link Sent",
    "portal.welcome": "Welcome, {name}",
    "portal.total_outstanding": "Total Balance",
    "portal.overdue_amount": "Overdue Balance",
    "portal.all_clear": "No Dues",
    "portal.last_payment": "Last Payment",
    "portal.next_due_date": "Next Due Date",
    "portal.invoice_number": "Invoice #",
    "portal.invoice_date": "Invoice Date",
    "portal.due_date": "Due Date",
    "portal.amount_paid": "Paid Amount",
    "portal.pay_now": "Pay Now",
    "portal.download_pdf": "Download PDF",
    "portal.payment_success": "Payment successful.",
    "portal.payment_error_declined": "Payment declined.",
    "portal.payment_error_generic": "Error processing payment.",
    "portal.link_expired": "Link expired.",
    "portal.request_new_link": "Request Link",
    "portal.verifying_access": "Verifying...",
    "portal.no_invoices": "No records.",
    "portal.partial_payment_label": "Partial Payment",
    "portal.select_payment_method": "Payment Method",
    "portal.auth_expired": "Session expired.",
    "portal.session_invalid": "Invalid session.",
    "portal.client_name": "Customer Name",
    "portal.party": "Party",
    "portal.status": "Status",
    "portal.never": "Never",
    "portal.active_nodes": "{count} active portals",
    "portal.initialize_access": "Grant Access",
    "portal.select_partner": "Select Party",
    "portal.select_party_placeholder": "Select Party...",
    "portal.access_email": "Access Email",
    "portal.display_name": "Display Name",
    "portal.dispatch_invite": "Send Invite",
    "stock.sku": "SKU",
    "stock.product_name": "Item Name",
    "stock.qty_on_hand": "Stock on Hand",
    "stock.location": "Location",
    "procurement.inventory_healthy": "Stock levels OK",
    "procurement.replenishment_alert": "Low Stock Alert",
    "procurement.items_below_reorder": "{count} items low",
    "procurement.total_est_value": "{value} total stock value",
    "procurement.view_all": "View All",
    "procurement.current_stock": "Current Stock",
    "procurement.shortfall": "Shortfall",
    "procurement.est_cost": "Est. Cost",
    "procurement.create_draft_po": "Create PO",
    "payroll.no_whatsapp": "No WhatsApp configured.",
    "payroll.salary_statement": "Salary Slip",
    "payroll.recipient_artisan": "Karigar",
    "payroll.period_label": "Month/Period",
    "payroll.earnings": "Earnings",
    "payroll.piece_rate": "Rate per Piece",
    "payroll.daily_wage": "Daily Wage",
    "payroll.monthly_base": "Base Salary",
    "payroll.overtime": "Overtime",
    "payroll.total_gross": "Gross Salary",
    "payroll.deductions": "Deductions",
    "payroll.advance_settled": "Peshgi Recovery",
    "payroll.eobi": "EOBI",
    "payroll.sessi": "SESSI",
    "payroll.other_adj": "Misc",
    "payroll.total_deductions": "Total Deductions",
    "payroll.net_disbursable": "Net Salary",
    "payroll.days_present": "Days Present",
    "payroll.total_output": "Total Output",
    "payroll.units": "Units",
    "payroll.efficiency": "Efficiency",
    "payroll.export_pdf": "Download Slip",
    "payroll.send_whatsapp": "WhatsApp Slip",
  }
};

