import jsPDF from 'jspdf'
import 'jspdf-autotable'

interface StatementData {
  businessName: string
  businessPhone?: string
  asOfDate: string
  period: { from: string; to: string }
  party: {
    name: string
    phone?: string
    address?: string
  }
  transactions: Array<{
    date: string
    type: 'invoice' | 'payment' | 'opening'
    reference: string
    description: string
    debit: number
    credit: number
    balance: number
  }>
  openingBalance: number
  closingBalance: number
  currency: string
}

export function generatePartyStatement(data: StatementData): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  const PAGE_W = 210
  const MARGIN = 15
  const fmt = (n: number) =>
    n === 0 ? '—' : `${data.currency} ${Math.abs(n).toLocaleString('en-PK')}`

  let y = MARGIN

  // Header
  doc.setFillColor(6, 7, 8)
  doc.rect(0, 0, PAGE_W, 32, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(data.businessName, MARGIN, 12)

  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  if (data.businessPhone) {
    doc.text(data.businessPhone, MARGIN, 19)
  }

  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(96, 165, 250)
  doc.text('ACCOUNT STATEMENT', PAGE_W - MARGIN, 14, { align: 'right' })

  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(180, 180, 180)
  doc.text(`Period: ${data.period.from} to ${data.period.to}`, PAGE_W - MARGIN, 21, { align: 'right' })

  y = 38

  // Party info + summary
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(80, 80, 80)
  doc.text('STATEMENT FOR:', MARGIN, y)

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0, 0, 0)
  doc.text(data.party.name, MARGIN, y + 7)

  if (data.party.phone) {
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 100, 100)
    doc.text(data.party.phone, MARGIN, y + 13)
  }

  // Closing balance box (top right)
  const isDebit = data.closingBalance > 0
  const boxColor = isDebit ? [254, 242, 242] : [240, 253, 244]
  const textColor = isDebit ? [185, 28, 28] : [21, 128, 61]

  doc.setFillColor(boxColor[0], boxColor[1], boxColor[2])
  doc.roundedRect(PAGE_W - MARGIN - 60, y - 2, 60, 24, 3, 3, 'F')

  doc.setFontSize(7)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(120, 120, 120)
  doc.text(
    isDebit ? 'BALANCE DUE' : 'CREDIT BALANCE',
    PAGE_W - MARGIN - 30,
    y + 5,
    { align: 'center' }
  )

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(textColor[0], textColor[1], textColor[2])
  doc.text(
    fmt(Math.abs(data.closingBalance)),
    PAGE_W - MARGIN - 30,
    y + 14,
    { align: 'center' }
  )

  y += 28

  // Transactions table
  ;(doc as any).autoTable({
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [['Date', 'Reference', 'Description', 'Debit', 'Credit', 'Balance']],
    body: [
      [data.period.from, '—', 'Opening Balance', '', '', fmt(data.openingBalance)],
      ...data.transactions.map(t => [
        t.date,
        t.reference,
        t.description,
        t.debit > 0 ? fmt(t.debit) : '',
        t.credit > 0 ? fmt(t.credit) : '',
        fmt(t.balance),
      ]),
    ],
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: {
      fillColor: [6, 7, 8],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 7.5,
    },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 28 },
      3: { halign: 'right', cellWidth: 28 },
      4: { halign: 'right', cellWidth: 28 },
      5: { halign: 'right', cellWidth: 28, fontStyle: 'bold' },
    },
    alternateRowStyles: { fillColor: [252, 252, 252] },
    didParseCell: (hookData: any) => {
      const row = hookData.row.raw
      if (row && row[1] && String(row[1]).startsWith('PMT')) {
        hookData.cell.styles.textColor = [21, 128, 61]
      }
    },
  })

  const finalY = (doc as any).lastAutoTable.finalY + 10

  // Closing summary
  doc.setFillColor(245, 245, 245)
  doc.rect(MARGIN, finalY, PAGE_W - MARGIN * 2, 14, 'F')
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0, 0, 0)
  doc.text(
    isDebit
      ? `Amount Due: ${fmt(Math.abs(data.closingBalance))}`
      : `Credit in Your Favor: ${fmt(Math.abs(data.closingBalance))}`,
    PAGE_W - MARGIN - 4,
    finalY + 9,
    { align: 'right' }
  )

  // Footer
  doc.setFontSize(7)
  doc.setTextColor(160, 160, 160)
  doc.text(
    `This is a computer-generated statement from ${data.businessName}. Generated by Noxis Hub.`,
    PAGE_W / 2,
    doc.internal.pageSize.height - 8,
    { align: 'center' }
  )

  doc.save(`Statement-${data.party.name}-${data.period.from}-to-${data.period.to}.pdf`)
}
