export type KnowledgeEntry = {
  id: string
  title: string
  category: string
  tags: string[]
  content: string
  route?: string
  action_label?: string
  shortcut?: string
  steps?: string[]
}

export const knowledgeBase: KnowledgeEntry[] = [

  // ─── NAVIGATION ───
  {
    id: 'nav-dashboard',
    title: 'Go to Dashboard',
    category: 'Navigation',
    tags: ['dashboard','home','main','overview','start','kpi','summary'],
    content: 'The Dashboard is your main overview page showing revenue, stock value, outstanding invoices, and today\'s activity.',
    route: '/dashboard',
    action_label: 'Open Dashboard',
  },
  {
    id: 'nav-inventory',
    title: 'Go to Inventory',
    category: 'Navigation',
    tags: ['inventory','stock','products','skus','maal','items','barcode','reorder'],
    content: 'Inventory shows all your products and stock levels. You can add, edit, and track every item.',
    route: '/inventory',
    action_label: 'Open Inventory',
  },
  {
    id: 'nav-karigars',
    title: 'Go to Karigars',
    category: 'Navigation',
    tags: ['karigars','workers','employees','staff','labour','labor','attendance','wages','karigar'],
    content: 'The Karigars module manages all your workers — attendance, piece-rate production, advances (peshgi), and payslips.',
    route: '/karigars',
    action_label: 'Open Karigars',
  },
  {
    id: 'nav-invoices',
    title: 'Go to Invoices',
    category: 'Navigation',
    tags: ['invoices','bills','sales','billing','receipt','document'],
    content: 'Invoices shows all your sales invoices. Create new invoices, view outstanding, and send via WhatsApp.',
    route: '/invoices',
    action_label: 'Open Invoices',
  },
  {
    id: 'nav-new-invoice',
    title: 'Create New Invoice',
    category: 'Navigation',
    tags: ['new invoice','create invoice','make bill','add invoice','invoice banao'],
    content: 'Opens the invoice creation form. Select a customer, add items, and finalize.',
    route: '/invoices/new',
    action_label: 'New Invoice',
    shortcut: 'N key on invoices page',
  },
  {
    id: 'nav-parties',
    title: 'Go to Parties',
    category: 'Navigation',
    tags: ['parties','customers','suppliers','vendors','clients','buyer','seller','customer','supplier'],
    content: 'Parties holds all your customers and suppliers with their balances and transaction history.',
    route: '/parties',
    action_label: 'Open Parties',
  },
  {
    id: 'nav-payroll',
    title: 'Go to Payroll',
    category: 'Navigation',
    tags: ['payroll','salary','tankhwa','wages','monthly pay','pay','payment'],
    content: 'Payroll calculates monthly wages for all workers automatically from attendance and production logs.',
    route: '/payroll',
    action_label: 'Open Payroll',
  },
  {
    id: 'nav-khata',
    title: 'Go to Khata (Ledger)',
    category: 'Navigation',
    tags: ['khata','ledger','accounts','hisab','accounting','journal','double entry'],
    content: 'Khata is the double-entry accounting ledger. Record cash, bank, and journal entries.',
    route: '/khata',
    action_label: 'Open Khata',
  },
  {
    id: 'nav-reports',
    title: 'Go to Reports',
    category: 'Navigation',
    tags: ['reports','profit loss','balance sheet','trial','aging','tax','p&l','financial report'],
    content: 'Reports shows Profit & Loss, Balance Sheet, Trial Balance, Aging, and Tax reports.',
    route: '/reports',
    action_label: 'Open Reports',
  },
  {
    id: 'nav-purchase',
    title: 'Go to Purchase',
    category: 'Navigation',
    tags: ['purchase','buy','order','supplier order','kharid','po'],
    content: 'Purchase manages purchase orders to suppliers and goods received notes.',
    route: '/purchase',
    action_label: 'Open Purchase',
  },
  {
    id: 'nav-production',
    title: 'Go to Production',
    category: 'Navigation',
    tags: ['production','output','pieces','floor','manufacturing','batch','factory'],
    content: 'Production logs daily output per worker, tracks batches, and shows efficiency analytics.',
    route: '/production',
    action_label: 'Open Production',
  },
  {
    id: 'nav-cashflow',
    title: 'Go to Cash Flow',
    category: 'Navigation',
    tags: ['cash','cashflow','forecast','liquidity','money','nakdi','cash forecast'],
    content: 'Cash Flow shows a 90-day forecast of your cash position so you can plan ahead.',
    route: '/cashflow',
    action_label: 'Open Cash Flow',
  },
  {
    id: 'nav-dispatch',
    title: 'Go to Dispatch',
    category: 'Navigation',
    tags: ['dispatch','delivery','shipment','outgoing','logistics'],
    content: 'Dispatch manages outgoing shipments and delivery tracking.',
    route: '/dispatch',
    action_label: 'Open Dispatch',
  },
  {
    id: 'nav-promises',
    title: 'Go to Payment Promises',
    category: 'Navigation',
    tags: ['promises','commitment','due','payment promise','overdue'],
    content: 'Payment Promises tracks verbal commitments from customers. Alerts you on the due date.',
    route: '/promises',
    action_label: 'Open Promises',
  },
  {
    id: 'nav-cctv',
    title: 'Go to CCTV',
    category: 'Navigation',
    tags: ['cctv','camera','security','surveillance','monitor','ai detection'],
    content: 'CCTV connects your IP cameras and provides AI-powered detection alerts. Currently in beta.',
    route: '/cctv',
    action_label: 'Open CCTV',
  },
  {
    id: 'nav-audit',
    title: 'Go to Audit & Compliance',
    category: 'Navigation',
    tags: ['audit','compliance','reconcile','fraud','change log','history','log'],
    content: 'Audit & Compliance provides inventory reconciliation and change history logs.',
    route: '/audit',
    action_label: 'Open Audit',
  },
  {
    id: 'nav-calculators',
    title: 'Go to Calculators',
    category: 'Navigation',
    tags: ['calculator','calculators','fabric','gsm','emi','oee','margin','piece rate','compute','calculate'],
    content: 'Industrial calculators for Fabric Consumption, Process Loss, Machine OEE, Piece Rate, Export Costing, and Delivery Planning.',
    route: '/calculators',
    action_label: 'Open Calculators',
    shortcut: 'Tools → Calculators',
  },
  {
    id: 'nav-converters',
    title: 'Go to Converters',
    category: 'Navigation',
    tags: ['converter','convert','currency','weight','fabric','measurement','unit'],
    content: 'Built-in converters for Currency, Weight, Fabric Length, GSM, Margin, Piece Rate, Container Load, and EMI.',
    route: '/converters',
    action_label: 'Open Converters',
  },
  {
    id: 'nav-import',
    title: 'Go to Import Data',
    category: 'Navigation',
    tags: ['import','upload','excel','csv','migrate','data'],
    content: 'Smart Data Import lets you upload Excel or CSV files and auto-maps columns to Noxis fields.',
    route: '/import',
    action_label: 'Open Import',
  },
  {
    id: 'nav-file-morph',
    title: 'Go to File Morph',
    category: 'Navigation',
    tags: ['file morph','compress','pdf','merge','convert','image','heic','jpg','file'],
    content: 'File Morph provides image compression, PDF merge, HEIC to JPG conversion, and format conversion tools.',
    route: '/file-morph',
    action_label: 'Open File Morph',
  },
  {
    id: 'nav-generators',
    title: 'Go to Generators',
    category: 'Navigation',
    tags: ['generator','generate','invoice generator','payslip','salary slip','purchase order','qr','barcode'],
    content: 'Generators create printable invoices, payslips, purchase orders, and QR/barcode labels.',
    route: '/generators/invoice',
    action_label: 'Open Generators',
  },
  {
    id: 'nav-intelligence',
    title: 'Go to Intelligence',
    category: 'Navigation',
    tags: ['intelligence','predict','forecast','benchmark','market','insight','analysis','ai'],
    content: 'Intelligence shows market benchmarks, stock-out predictions, customer churn risks, and margin alerts.',
    route: '/intelligence',
    action_label: 'Open Intelligence',
  },
  {
    id: 'nav-finance',
    title: 'Go to Working Capital / Finance',
    category: 'Navigation',
    tags: ['finance','loan','credit','capital','working capital','funding','bank'],
    content: 'Working Capital shows your finance score and connects you with loan referrals.',
    route: '/finance',
    action_label: 'Open Finance',
  },
  {
    id: 'nav-network',
    title: 'Go to Factory Network',
    category: 'Navigation',
    tags: ['network','factory network','connect','marketplace','b2b','supply chain'],
    content: 'Factory Network connects you with verified factories for B2B trade, supplier sourcing, and collaboration.',
    route: '/network',
    action_label: 'Open Network',
  },
  {
    id: 'nav-settings',
    title: 'Go to Settings',
    category: 'Navigation',
    tags: ['settings','configure','profile','preferences','setup'],
    content: 'Settings lets you configure your business profile, language, theme, backup, and integrations.',
    route: '/settings',
    action_label: 'Open Settings',
    shortcut: 'Bottom of sidebar',
  },
  {
    id: 'nav-backup',
    title: 'Go to Backup & Restore',
    category: 'Navigation',
    tags: ['backup','restore','export','download','data','safety'],
    content: 'Backup & Restore lets you download an encrypted backup and restore your data.',
    route: '/settings/backup',
    action_label: 'Open Backup',
  },
  {
    id: 'nav-quick-entry',
    title: 'Go to Quick Entry',
    category: 'Navigation',
    tags: ['quick entry','fast','rapid','piece','attendance','payment record','quick'],
    content: 'Quick Entry Hub lets you rapidly log production, record payments, and mark attendance from one screen.',
    route: '/quick-entry',
    action_label: 'Open Quick Entry',
    shortcut: 'Space bar anywhere',
  },
  {
    id: 'nav-pairing',
    title: 'Go to Mobile Pairing',
    category: 'Navigation',
    tags: ['mobile pair','android connect','qr pair','phone connect','mobile app','pairing'],
    content: 'Pairing shows a QR code that pairs your Android phone with Noxis Hub over WiFi.',
    route: '/pairing',
    action_label: 'Open Pairing',
  },

  // ─── HOW TO USE ───
  {
    id: 'how-add-karigar',
    title: 'How to add a Karigar (worker)',
    category: 'How To',
    tags: ['add karigar','new worker','register worker','how karigar','karigar kaise','karigar add'],
    content: 'To add a new Karigar: Go to Karigars module, click Add Karigar button. Enter the worker\'s name, phone number, and select wage type — piece rate, daily, or monthly. Enter the rate. Click Save. The system auto-generates a Karigar code.',
    route: '/karigars',
    action_label: 'Go to Karigars',
    shortcut: 'Space → Add Karigar',
    steps: [
      'Open Karigars from the sidebar',
      'Click + Add Karigar (top right)',
      'Enter name and phone number',
      'Select wage type: Piece Rate, Daily, or Monthly',
      'Enter the rate amount',
      'Click Save',
    ],
  },
  {
    id: 'how-peshgi',
    title: 'How to give Peshgi (advance)',
    category: 'How To',
    tags: ['peshgi','advance','loan','worker advance','give advance','peshgi do','advance payment'],
    content: 'Peshgi is an advance payment to a worker deducted from their next salary. To give Peshgi: press Space bar anywhere and select Give Advance. Or go to Karigars, click the worker, go to Advances tab, click New Advance. Enter amount and reason. It auto-deducts from payroll.',
    route: '/karigars',
    action_label: 'Go to Karigars',
    shortcut: 'Space → Give Advance',
    steps: [
      'Press Space bar and select Give Advance',
      'OR: Open Karigars → click worker → Advances tab',
      'Click New Advance',
      'Enter amount (e.g. PKR 5,000)',
      'Enter reason (Medical, Festival, etc.)',
      'Click Save — auto-deducts from next payroll',
    ],
  },
  {
    id: 'how-piece-rate',
    title: 'How piece rate wages work',
    category: 'How To',
    tags: ['piece rate','how piece rate','tukra','per piece','wage calculate','piece rate kaise'],
    content: 'Piece rate pays workers per unit they produce. Set the rate when adding a Karigar (e.g. PKR 25 per piece). When production is logged, earnings calculate automatically. At month end, payroll sums all earnings minus any Peshgi advances.',
    steps: [
      'Set piece rate when adding Karigar (e.g. PKR 25/piece)',
      'Log production daily: worker name + units + grade',
      'System calculates: 200 pieces × PKR 25 = PKR 5,000',
      'At month end run payroll — deducts Peshgi automatically',
      'Generate payslip and send via WhatsApp',
    ],
  },
  {
    id: 'how-create-invoice',
    title: 'How to create an invoice',
    category: 'How To',
    tags: ['create invoice','make invoice','new invoice','how invoice','invoice banao','bill banao'],
    content: 'To create an invoice: Go to Invoices and click New Invoice. Search for the customer by typing their name. Add line items by typing the product name. Set quantities and prices. The live preview updates in real time. Click Finalize and Post to save. The ledger updates automatically.',
    route: '/invoices/new',
    action_label: 'Create Invoice',
    shortcut: 'N key on invoices page',
    steps: [
      'Go to Invoices → New Invoice',
      'Type customer name in the Customer field',
      'Select the customer from dropdown',
      'Type product name to add a line item',
      'Set quantity and rate',
      'Review the live preview on the right',
      'Click Finalize and Post',
    ],
  },
  {
    id: 'how-add-stock',
    title: 'How to add or adjust stock',
    category: 'How To',
    tags: ['add stock','adjust stock','stock update','qty','quantity','maal add','inventory add'],
    content: 'To add a new product: go to Inventory and click Add SKU. To adjust existing stock: click the product, then click Adjust Stock and enter the new quantity. All adjustments are logged in the audit trail.',
    route: '/inventory',
    action_label: 'Go to Inventory',
    shortcut: 'Space → Adjust Stock',
    steps: [
      'Go to Inventory from sidebar',
      'To add new: click + Add SKU',
      'To adjust existing: click the product row',
      'Click Adjust Stock button',
      'Enter the new total quantity',
      'Click Save — audit trail logs the change',
    ],
  },
  {
    id: 'how-payroll',
    title: 'How to run monthly payroll',
    category: 'How To',
    tags: ['run payroll','payroll karo','monthly salary','calculate wages','how payroll','salary calculate'],
    content: 'To run payroll: Go to Payroll module and click Run Payroll Period. Select the month. The system pulls attendance records and production logs automatically. Review each worker\'s earnings and Peshgi deductions. Click Confirm to finalize. Generate payslips for all workers.',
    route: '/payroll',
    action_label: 'Go to Payroll',
    steps: [
      'Go to Payroll from sidebar',
      'Click Run Payroll Period',
      'Select the month',
      'Review each worker\'s auto-calculated wages',
      'Check Peshgi deductions are correct',
      'Click Confirm to post payroll',
      'Click Generate Payslips to create PDFs',
    ],
  },
  {
    id: 'how-reports',
    title: 'How to view financial reports',
    category: 'How To',
    tags: ['view reports','profit loss','how reports','financial report','pl report','report dekho'],
    content: 'Go to Reports in the sidebar. Choose from: Profit & Loss, Balance Sheet, Trial Balance, Aging Report, Tax Report, or Export Center. Select your date range. The report generates automatically. You can export to CSV or print.',
    route: '/reports',
    action_label: 'Open Reports',
    steps: [
      'Go to Reports from sidebar',
      'Select report type (e.g. Profit & Loss)',
      'Set the date range',
      'Click Generate or it auto-generates',
      'Export to CSV or Print as needed',
    ],
  },
  {
    id: 'how-attendance',
    title: 'How to mark attendance',
    category: 'How To',
    tags: ['attendance','mark present','absent','haazri','how attendance','attendance lagao'],
    content: 'Mark attendance from Quick Entry Hub: press Space and select Mark Attendance. Or go to Karigars, click a worker, go to Attendance tab. Mark Present, Absent, or Half Day. The mobile app can also mark attendance with one tap.',
    route: '/quick-entry',
    action_label: 'Quick Entry',
    shortcut: 'Space → Mark Attendance',
    steps: [
      'Press Space → Mark Attendance (fastest way)',
      'OR: Open Karigars → click worker → Attendance tab',
      'Select today\'s date',
      'Mark: Present, Absent, or Half Day',
      'Save — reflects in payroll automatically',
    ],
  },
  {
    id: 'how-production-log',
    title: 'How to log production',
    category: 'How To',
    tags: ['log production','piece entry','units produced','production log','production karo','pieces lagao'],
    content: 'Log production from Quick Entry or the Production module. Select the Karigar, enter units produced, select grade (A, B, C, or Rejected). The system calculates earnings based on their piece rate. Run this daily for accurate payroll.',
    route: '/quick-entry',
    action_label: 'Quick Entry',
    shortcut: 'Space → Log Production',
    steps: [
      'Press Space → Log Production (fastest)',
      'OR: Go to Production module',
      'Select the Karigar',
      'Enter units produced',
      'Select quality grade: A, B, C, or Rejected',
      'Click Save — earnings auto-calculated',
    ],
  },
  {
    id: 'how-backup',
    title: 'How to backup your data',
    category: 'How To',
    tags: ['backup','save data','export data','data safety','restore','data backup'],
    content: 'Go to Settings → Backup & Restore. Click Download Backup to save an encrypted copy of all your data. You can also set it to auto-backup every Sunday. To restore, upload the backup file and click Restore.',
    route: '/settings/backup',
    action_label: 'Go to Backup',
    steps: [
      'Go to Settings → Backup & Restore',
      'Click Download Backup',
      'Set a password for encryption (optional)',
      'Save the file somewhere safe',
      'Auto-backup runs every Sunday at 2 AM',
    ],
  },
  {
    id: 'how-whatsapp',
    title: 'How to send via WhatsApp',
    category: 'How To',
    tags: ['whatsapp send','send invoice whatsapp','whatsapp message','share','whatsapp karo'],
    content: 'On any invoice, party, or karigar page there is a WhatsApp button. Click it to open WhatsApp with a pre-filled message. No API setup needed — it uses your existing WhatsApp. For automated daily summaries, configure in Settings → WhatsApp Alerts.',
    steps: [
      'Open any invoice or party page',
      'Click the WhatsApp button',
      'WhatsApp opens with pre-filled message',
      'Press Send — that\'s it',
      'For auto-summaries: Settings → WhatsApp Alerts',
    ],
  },
  {
    id: 'how-language',
    title: 'How to switch to Urdu',
    category: 'How To',
    tags: ['urdu','language','zaban','switch language','rtl','nastaliq','urdu karo'],
    content: 'Click the language selector in the top header bar (shows EN or اردو). Select Urdu to switch the entire interface to Nastaliq script with right-to-left layout. All sidebar labels, buttons, and menus change to Urdu.',
    shortcut: 'EN | اردو toggle in header',
    steps: [
      'Click EN in the top header',
      'Select اردو (Urdu)',
      'Interface switches to Nastaliq RTL',
      'All menus and labels change to Urdu',
      'Switch back to EN at any time',
    ],
  },
  {
    id: 'how-theme',
    title: 'How to change the theme or colors',
    category: 'How To',
    tags: ['theme','color','change color','dark','appearance','look','rang badlo'],
    content: 'Press Ctrl+T anywhere to open the theme picker. Choose from 20 industrial themes. The colors change instantly. You can also go to Settings → Appearance. The selected theme saves permanently.',
    shortcut: 'Ctrl + T',
    steps: [
      'Press Ctrl+T anywhere in the app',
      'Choose from 20 themes',
      'Colors change immediately',
      'Theme saves automatically',
    ],
  },
  {
    id: 'how-mobile-pair',
    title: 'How to pair the mobile app',
    category: 'How To',
    tags: ['mobile pair','android connect','qr pair','phone connect','mobile app','phone joro'],
    content: 'Go to Pairing in the sidebar. A QR code appears on screen. On your Android phone, open Noxis Mobile and tap Scan QR. Point the camera at the QR code. The phone connects to the Hub instantly. Both devices must be on the same WiFi network.',
    route: '/pairing',
    action_label: 'Open Pairing',
    steps: [
      'On Hub PC: go to Pairing in sidebar',
      'A QR code appears on screen',
      'On Android: open Noxis Mobile',
      'Tap Scan QR and point at the QR code',
      'Connection established — both online',
      'Both devices must be on the same WiFi',
    ],
  },
  {
    id: 'how-calculator-use',
    title: 'How to use the calculators',
    category: 'How To',
    tags: ['use calculator','fabric calculator','emi calculator','how calculator','calculator use karo'],
    content: 'Go to Tools → Calculators. Six industrial calculators are available: Fabric Consumption (how much fabric for X shirts), Process Loss Tracker, Machine OEE Monitor, Piece Rate Calculator, Export Costing, and Delivery Planner. Click any calculator card to open it on the right side.',
    route: '/calculators',
    action_label: 'Open Calculators',
    steps: [
      'Go to Calculators from the sidebar',
      'Click any calculator card to open it',
      'Enter your values in the form',
      'Results calculate in real time',
      'Six calculators: Fabric, Loss, OEE, Piece Rate, Export, Delivery',
    ],
  },
  {
    id: 'how-add-party',
    title: 'How to add a customer or supplier',
    category: 'How To',
    tags: ['add customer','add supplier','new party','customer add','vendor add','party banao'],
    content: 'Go to Parties and click Add Party. Choose type: Customer or Supplier. Enter name, phone, address, and opening balance. Click Save. The party will appear in invoices and purchase orders automatically.',
    route: '/parties',
    action_label: 'Go to Parties',
    steps: [
      'Go to Parties from sidebar',
      'Click + Add Party',
      'Select type: Customer or Supplier',
      'Enter name, phone, address',
      'Enter opening balance if any',
      'Click Save',
    ],
  },
  {
    id: 'how-purchase-order',
    title: 'How to create a purchase order',
    category: 'How To',
    tags: ['purchase order','buy from supplier','po create','kharid order','order karo'],
    content: 'Go to Purchase and click New Purchase Order. Select your supplier. Add the items you want to buy with quantities and rates. Click Save to record the PO. When goods arrive, use Receive Goods to update inventory.',
    route: '/purchase',
    action_label: 'Go to Purchase',
    steps: [
      'Go to Purchase from sidebar',
      'Click New Purchase Order',
      'Select supplier',
      'Add items with qty and rate',
      'Click Save to create PO',
      'When goods arrive: click Receive Goods',
    ],
  },
  {
    id: 'how-quick-entry',
    title: 'How to use Quick Entry',
    category: 'How To',
    tags: ['quick entry how','space bar','fast entry','rapid log','space use'],
    content: 'Press the Space bar from anywhere in the app to open Quick Entry. It shows buttons for: Log Production, Record Payment, Mark Attendance, and Give Advance. This is the fastest way to do daily tasks without navigating menus.',
    route: '/quick-entry',
    action_label: 'Open Quick Entry',
    shortcut: 'Space bar (from anywhere)',
    steps: [
      'Press Space bar from any screen',
      'Choose: Log Production, Record Payment, Mark Attendance, or Give Advance',
      'Fill in the quick form',
      'Click Save — done in under 30 seconds',
    ],
  },

  // ─── KEYBOARD SHORTCUTS ───
  {
    id: 'shortcut-all',
    title: 'Keyboard shortcuts',
    category: 'Shortcuts',
    tags: ['shortcut','keyboard','ctrl k','space','hotkey','quick','ctrl t','shortcuts list'],
    content: 'Noxis has built-in keyboard shortcuts: Ctrl+K opens global search, Space bar opens Quick Actions, Ctrl+T changes theme, Ctrl+/ opens the Knowledge Assistant (Ask Noxis), Ctrl+N creates a new item on list pages.',
    steps: [
      'Ctrl+K — Global search',
      'Space — Quick Actions menu',
      'Ctrl+T — Theme picker',
      'Ctrl+/ — Ask Noxis assistant',
      'Ctrl+N — New item (on list pages)',
    ],
  },

  // ─── GENERAL QUESTIONS ───
  {
    id: 'what-is-noxis',
    title: 'What is Noxis?',
    category: 'General',
    tags: ['what is noxis','about noxis','noxis kya hai','explain noxis','hello','what can you do','noxis'],
    content: 'Noxis is an industrial ERP (factory management software) built by Omnora Labs. It manages inventory, karigar wages, invoices, purchase orders, accounts, CCTV cameras, and mobile devices — all working offline without internet. I am the Noxis AI assistant. I can help you navigate the software, explain features, and answer questions about how to use it.',
  },
  {
    id: 'what-is-omnora',
    title: 'Who made Noxis?',
    category: 'General',
    tags: ['omnora','who made','developer','company','creator','ahmad mahboob','maker'],
    content: 'Noxis is developed by Omnora Labs, based in Pakistan. The founder is Ahmad Mahboob. Omnora Labs builds industrial software for South Asian and global manufacturing businesses.',
  },
  {
    id: 'pricing-info',
    title: 'What are the pricing plans?',
    category: 'General',
    tags: ['price','pricing','cost','plan','lite','pro','elite','how much','kitna','subscription'],
    content: 'Noxis has three plans: Lite at PKR 2,500/month (5 devices, 2 cameras, basic features), Pro at PKR 6,500/month (15 devices, 8 cameras with AI, WhatsApp summaries, 5 staff users), and Elite at PKR 14,000/month (50 devices, 20 cameras, unlimited staff, fire detection). All plans start with a 3-day free trial.',
    route: '/pricing',
    action_label: 'View Pricing',
  },
  {
    id: 'offline-mode',
    title: 'Does Noxis work offline?',
    category: 'General',
    tags: ['offline','internet','no internet','without internet','offline kaam','offline mode'],
    content: 'Yes! Noxis is offline-first. All data is stored locally on your device. You can create invoices, run payroll, log production, and view reports without any internet connection. Data syncs to the cloud automatically when internet is available.',
  },
  {
    id: 'multi-device',
    title: 'Can I use Noxis on multiple devices?',
    category: 'General',
    tags: ['multiple devices','multi device','two computers','devices','staff devices'],
    content: 'Yes. Your Lite plan includes 5 devices, Pro includes 15, and Elite includes 50. Each device connects to the same business account. Use Mobile Pairing to add Android phones. Staff users can get their own login with restricted access.',
  },
]
