import Link from 'next/link'
import { BookOpen, Shield, ChevronLeft } from 'lucide-react'

export const metadata = {
  title: 'Terms of Service | Noxis Hub',
  description: 'Read the Terms of Service for Noxis Hub — the industrial ERP platform by Omnora Labs. Understand your rights, responsibilities, and usage policies.',
}

const SECTIONS = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    body: [
      'By downloading, installing, or using Noxis Hub ("Software"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Software.',
      'These Terms apply to all users, including business owners, staff accounts, and mobile device users connected to a Noxis Hub instance.',
    ],
  },
  {
    id: 'license',
    title: '2. License Grant',
    body: [
      'Omnora Labs grants you a limited, non-exclusive, non-transferable, revocable license to use Noxis Hub solely for your internal business operations during the active subscription period.',
      'Your license covers the number of devices and users permitted by your current plan (Lite, Pro, or Elite). Installing on more devices than your plan allows is a breach of these Terms.',
      'You may not sub-license, sell, resell, transfer, assign, or commercially exploit the Software in any way without prior written consent from Omnora Labs.',
    ],
  },
  {
    id: 'subscription',
    title: '3. Subscription & Billing',
    body: [
      'Noxis Hub is offered on a monthly subscription basis. All fees are billed in advance and are non-refundable except where required by applicable law.',
      'Your subscription renews automatically each month unless you cancel at least 7 days before the renewal date.',
      'Omnora Labs reserves the right to change pricing with 30 days\' notice. Continued use after a price change constitutes acceptance of the new pricing.',
      'The 3-day free trial provides full Elite-tier access. No credit card is required during the trial period. After 3 days, the account reverts to read-only mode until a plan is selected.',
    ],
  },
  {
    id: 'data',
    title: '4. Your Data & Privacy',
    body: [
      'You retain full ownership of all business data entered into Noxis Hub, including inventory records, financial entries, employee data, and customer information.',
      'Noxis Hub stores data locally on your device by default. Cloud Sync features are opt-in and governed separately by our Privacy Policy.',
      'We do not sell, share, or monetise your business data. Data is only processed to deliver the Software functionality you request.',
      'You are responsible for maintaining regular backups. Use Settings → Backup & Restore to export an encrypted copy of your data.',
    ],
  },
  {
    id: 'prohibited',
    title: '5. Prohibited Uses',
    body: [
      'You may not use Noxis Hub to store or process any unlawful, defamatory, fraudulent, or harmful content.',
      'Reverse engineering, decompiling, or disassembling the Software is strictly prohibited.',
      'Using the Software to build a competing product or to extract proprietary algorithms is not permitted.',
      'Sharing login credentials between businesses or using one account for multiple unrelated business entities is not permitted.',
    ],
  },
  {
    id: 'support',
    title: '6. Support & Updates',
    body: [
      'Omnora Labs provides support via WhatsApp (+92 333 4355475) and email during business hours (Mon–Sat, 9 AM – 6 PM PKT).',
      'Software updates are provided automatically and may include new features, bug fixes, or security patches. Major version updates may require a plan upgrade.',
      'Support response times: Pro and Elite plans receive priority support (within 4 hours). Lite plans receive standard support (within 24 hours).',
    ],
  },
  {
    id: 'disclaimer',
    title: '7. Disclaimer of Warranties',
    body: [
      'The Software is provided "as is" without warranty of any kind, express or implied. Omnora Labs does not warrant that the Software will be error-free, uninterrupted, or that defects will be corrected.',
      'Omnora Labs is not responsible for any business decisions made based on reports, forecasts, or analytics generated by the Software.',
    ],
  },
  {
    id: 'liability',
    title: '8. Limitation of Liability',
    body: [
      'To the maximum extent permitted by law, Omnora Labs shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Software.',
      'Omnora Labs\' total cumulative liability for any claims relating to the Software shall not exceed the total fees paid by you in the 3 months immediately preceding the claim.',
    ],
  },
  {
    id: 'termination',
    title: '9. Termination',
    body: [
      'You may cancel your subscription at any time from the Settings → Billing panel. Cancellation takes effect at the end of the current billing period.',
      'Omnora Labs may suspend or terminate your access immediately if you violate these Terms, engage in fraudulent activity, or fail to pay subscription fees.',
      'Upon termination, you may export your data within 30 days. After that period, data may be permanently deleted.',
    ],
  },
  {
    id: 'governing',
    title: '10. Governing Law',
    body: [
      'These Terms are governed by and construed in accordance with the laws of Pakistan. Any disputes shall be subject to the exclusive jurisdiction of the courts of Lahore, Punjab, Pakistan.',
      'If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.',
    ],
  },
  {
    id: 'changes',
    title: '11. Changes to Terms',
    body: [
      'We may update these Terms from time to time. We will notify you via the in-app notification system or email at least 14 days before material changes take effect.',
      'Your continued use of Noxis Hub after changes take effect constitutes your acceptance of the revised Terms.',
    ],
  },
  {
    id: 'contact',
    title: '12. Contact',
    body: [
      'If you have questions about these Terms, please contact Omnora Labs:',
      'WhatsApp: +92 333 4355475',
      'Email: support@noxishub.app',
      'Address: Omnora Labs, Lahore, Pakistan',
    ],
  },
]

export default function TermsOfServicePage() {
  return (
    <div className="bg-[#121417] min-h-screen text-slate-300 font-inter pb-32">
      {/* Subtle radial glow */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-[500px] bg-[radial-gradient(circle_at_center,rgba(96,165,250,0.05)_0%,transparent_70%)] pointer-events-none" />

      {/* Navigation */}
      <nav className="relative top-0 w-full z-50 bg-[#121417]/85 backdrop-blur-xl border-b border-white/5 py-4">
        <div className="max-w-7xl mx-auto px-6 flex items-center justify-between">
          <Link href="/" className="flex items-center space-x-3 group cursor-pointer">
            <div className="w-10 h-10 flex items-center justify-center bg-white/5 group-hover:bg-electric-blue/10 rounded-sm transition-all">
              <img src="/logos/noxis.png" alt="Noxis Logo" width={32} height={32} className="object-contain" />
            </div>
            <span className="text-white font-black tracking-tighter text-xl">NOXIS</span>
          </Link>
          <div className="flex items-center space-x-8 text-[11px] font-bold uppercase tracking-[0.15em] text-white/50">
            <Link href="/blog" className="hover:text-[#60A5FA] transition-colors flex items-center gap-2">
              <BookOpen className="w-3.5 h-3.5" />
              Blog
            </Link>
            <Link href="/privacy" className="hover:text-[#60A5FA] transition-colors">Privacy</Link>
          </div>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 mt-14 relative z-10">
        {/* Back link */}
        <Link
          href="/blog"
          className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-slate-500 hover:text-[#60A5FA] transition-colors mb-10"
        >
          <ChevronLeft className="w-4 h-4" />
          Back to Blog
        </Link>

        {/* Header */}
        <header className="mb-14 border-b border-white/5 pb-10">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-sm bg-[#60A5FA]/10 flex items-center justify-center">
              <Shield className="w-5 h-5 text-[#60A5FA]" />
            </div>
            <span className="text-[10px] font-black uppercase tracking-widest text-[#60A5FA]">Legal</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-black text-white tracking-tight leading-tight mb-4">
            Terms of Service
          </h1>
          <p className="text-slate-400 text-base font-medium">
            Last updated: June 2026 · Effective immediately for all new and existing accounts.
          </p>
          <p className="mt-4 text-slate-400 text-sm leading-relaxed max-w-2xl">
            Please read these Terms carefully before using Noxis Hub. By using the Software, you agree to these Terms.
            If you are using Noxis Hub on behalf of a business, you represent that you have authority to bind that business to these Terms.
          </p>
        </header>

        {/* Table of Contents */}
        <nav className="mb-14 p-6 bg-white/[0.03] border border-white/8 rounded-sm">
          <p className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-4">Contents</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {SECTIONS.map(s => (
              <a
                key={s.id}
                href={`#${s.id}`}
                className="text-sm text-slate-400 hover:text-[#60A5FA] transition-colors flex items-center gap-2"
              >
                <span className="text-[#60A5FA] text-xs">›</span>
                {s.title}
              </a>
            ))}
          </div>
        </nav>

        {/* Sections */}
        <article className="space-y-14">
          {SECTIONS.map(section => (
            <section key={section.id} id={section.id} className="scroll-mt-20">
              <h2 className="text-xl md:text-2xl font-black text-white tracking-tight mb-5 border-b border-white/5 pb-3">
                {section.title}
              </h2>
              <div className="space-y-4">
                {section.body.map((para, i) => (
                  <p key={i} className="text-slate-300 leading-relaxed text-base font-medium">
                    {para}
                  </p>
                ))}
              </div>
            </section>
          ))}
        </article>

        {/* Footer CTA */}
        <div className="mt-20 p-10 bg-[#1A1D21] border border-white/5 rounded-sm flex flex-col md:flex-row items-center justify-between gap-8">
          <div className="space-y-2">
            <h3 className="text-lg font-black text-white uppercase tracking-widest">Questions about these Terms?</h3>
            <p className="text-sm text-slate-400 font-medium max-w-lg">
              Contact our support team via WhatsApp or email. We are happy to explain any clause.
            </p>
          </div>
          <a
            href="https://wa.me/923334355475?text=Hi%2C%20I%20have%20a%20question%20about%20the%20Noxis%20Terms%20of%20Service."
            target="_blank"
            rel="noopener noreferrer"
            className="bg-[#25D366] text-black px-8 py-4 font-black uppercase tracking-widest text-xs hover:brightness-110 shadow-[0_0_20px_rgba(37,211,102,0.2)] transition-all shrink-0"
          >
            WhatsApp Us
          </a>
        </div>

        {/* Footer links */}
        <div className="mt-12 pt-8 border-t border-white/5 flex flex-wrap items-center justify-between gap-4 text-xs text-slate-600 font-bold uppercase tracking-widest">
          <span>© {new Date().getFullYear()} Omnora Labs. All rights reserved.</span>
          <div className="flex items-center gap-6">
            <Link href="/privacy" className="hover:text-slate-400 transition-colors">Privacy Policy</Link>
            <Link href="/blog" className="hover:text-slate-400 transition-colors">Blog</Link>
            <Link href="/download" className="hover:text-[#60A5FA] transition-colors">Download</Link>
          </div>
        </div>
      </main>
    </div>
  )
}
